### PR TITLE
specr version 1.0.0 - New framework and parallelization

### PR DESCRIPTION
**Pull request by masurp**
Major update to specr. This version 1.0.0 breaks with earlier version to allow for more flexibility and speed. For details see below. 

### Breaking changes

- This new version introduces a completely new analytic framework which breaks with earlier versions of specr. See [this vignette](https://masurp.github.io/specr/articles/specr.html) for a comprehensive tutorial on how to use this new framework.

- A new function called [setup()](https://github.com/masurp/specr/reference/setup.html) is introduced and replaces the original [setup_specs()](https://github.com/masurp/specr/reference/setup_specs.html) to make the specification of analytical choices more intuitive and comprehensive. Most importantly, it allows to set up all specifications (now also including subset analyses, additions to the formula, etc.) a priori, i.e., before the estimation of all models.

   - Data, analytic choices, and even parameter extraction functions can be specified before the fitting process (solving github issue [#26](https://github.com/masurp/specr/issues/26)).
   - Excludes some non-meaningful specifications automatically (e.g., when control and independent or dependent variable are the same).
   - Allows to specify all combinations of control variables or to “simplify” and only include none, each individually and all together (github issue [#11](https://github.com/masurp/specr/issues/11)).
   - Resulting specification can be filtered using standard tidyverse functions such as e.g., [filter()](https://rdrr.io/r/stats/filter.html). This way, one can make sure a priori that only reasonable specifications are actually included.
   - Produces an object of class specr.setup, which can be investigated using e.g., [summary()](https://rdrr.io/r/base/summary.html).

- The function [run_specs()](https://github.com/masurp/specr/reference/run_specs.html) is replaced by [specr()](https://github.com/masurp/specr/reference/specr.html), which now only wraps around [setup()](https://github.com/masurp/specr/reference/setup.html) to estimate all models. Most changes are related to increasing speed of the computations.

   - Most importantly, the estimation process can now be parallelized (based on furrr) to reduce fitting time (finally solving github issue [#1](https://github.com/masurp/specr/issues/1)).
   - Deals better and faster with subset analyses.
   - Produces an object of class specr.object, which can be investigated using generic function such as [summary()](https://rdrr.io/r/base/summary.html) and [plot()](https://rdrr.io/r/graphics/plot.default.html).

- For more information about these major changes and how to use the new version of specr, see this [vignette](https://masurp.github.io/specr/articles/specr.html).

- Please note that the functions from earlier versions are still available, but deprecated. It is hence still possible to use the older framework as implemented in version 0.2.1, but we suggest to move to the new framework of version 0.3.0 due to its increased speed and flexibility.

### Known issues/bugs

- So far none…

### Acknowledgements

This version of specr was something I wanted to tackle for a while. Although the previous versions seem to have embraced by the community and several relevant papers used them in interesting ways, certain issues kept coming up (ranging from slow fitting process to wanting to incorporate more complex analytical decisions and choices). This version is thus heavily inspired by the growing community of scholars who provide feedback and suggestions via [github](https://github.com/masurp/specr/issues). Thank you to all of you! But for this version, I want to thank two people particularly:

- Big thanks go to [Matti Vuorre](https://github.com/mvuorre) who explored ways to parallelize specification curve analysis in this [blogpost](https://vuorre.netlify.app/posts/parallel-multiverse/), which became the basis for the implementation in specr.

- Thanks also to [Kasper Welbers](https://github.com/kasperwelbers) who contributed some essential code within the core function.

### Status & Request

This version produces 0 error | 0 warning | 0 notes during R CMD check. Before I merge with the master, it would be great if it could be reviewed (@mvuorre, @mscharkow). Thanks!

### CODE REVIEW

**Comment by akarlinsky** [comment]
This update sounds amazing! But when I try to go to the vignette, it still shows me the 0.2.2 version with `setup_specs` etc.?

**Comment by masurp** [comment]
> 

The website is updated in the branch, but obviously not yet live. Hence the link to the old version. First glimpse of the framework and how it works can be seen here: https://github.com/masurp/specr/tree/add_parallelization

The moment I'll actually merge it, you can also see the new website/vignettes.

**Comment by mvuorre** [comment]
Great work @masurp 😄 Happy that you were able to implement this! Just a quick note: You might want to switch to v1.0 to indicate breaking changes (https://semver.org/). I am also happy to take a look if needed but on a quick glance this looks sweet. 👏

**Comment by mvuorre** [comment]
I've got some small notes

- Is it necessary to do a [conditional](https://github.com/masurp/specr/blob/a4d8318fba30ea8be9e6befc6b473d9873c9d0be/R/specr.R#L157) based on number of workers? By default, `future_map()` defaults to sequential processing so you could do it in one call.
- Consider allowing users to set the [plan](https://github.com/masurp/specr/blob/a4d8318fba30ea8be9e6befc6b473d9873c9d0be/R/specr.R#L161). If none is set, it will just do sequential processing. If they do a plan before calling specr, then it will process in parallel. It would also allow users to set e.g. multicore or whatever. And using all available cores is not a good idea, since it won't leave any for the parent process, and on Linux the default call will use hyperthreading so twice the cores the user actually has.

**Comment by masurp** [comment]
> I've got some small notes
> 
> * Is it necessary to do a [conditional](https://github.com/masurp/specr/blob/a4d8318fba30ea8be9e6befc6b473d9873c9d0be/R/specr.R#L157) based on number of workers? By default, `future_map()` defaults to sequential processing so you could do it in one call.
> * Consider allowing users to set the [plan](https://github.com/masurp/specr/blob/a4d8318fba30ea8be9e6befc6b473d9873c9d0be/R/specr.R#L161). If none is set, it will just do sequential processing. If they do a plan before calling specr, then it will process in parallel. It would also allow users to set e.g. multicore or whatever. And using all available cores is not a good idea, since it won't leave any for the parent process, and on Linux the default call will use hyperthreading so twice the cores the user actually has.

Good point. I just added a second version of the core function called `specr2()`, which is no longer conditional on workers and requires the user to set the plan upfront. However, it seems that if no plan is specified, it is actually slower to use sequential `future_pmap()` compared to simply `pmap()`...

screenshot

**Comment by mvuorre** [comment]
Looks like future_* adds some overhead even when there is no parallelization. I am just thinking of this advice in the [future docs](https://future.futureverse.org/reference/plan.html):

>Please refrain from modifying the future strategy inside your packages / functions, i.e. do not call plan() in your code. Instead, leave the control on what backend to use to the end user. This idea is part of the core philosophy of the future framework - as a developer you can never know what future backends the user have access to. Moreover, by not making any assumptions about what backends are available, your code will also work automatically with any new backends developed after you wrote your code.
If you think it is necessary to modify the future strategy within a function, then make sure to undo the changes when exiting the function. 

So if possible those should be left for the user. Maybe you can e.g. check if a plan has been set and then use future_*, otherwise the purrr variant.

**Comment by masurp** [comment]
Yep. I just microbenchmarked the performance of both approaches and future_* indeed adds overhead even when there is no parallelization. 

But I agree, let's not put the plan into the function. I'll rewrite and recommit. Thanks for the feedback! ;)

**Comment by mvuorre** [comment]
You can e.g. use `is(plan(), "sequential")`to check if a multi* plan is set and only then use the future variant.

**Comment by masurp** [comment]
So based on your guys' feedback, I implemented a couple of changes:

## Response to @mvuorre:
- Setting up a future plan (e.g., `plan(multisession, workers = 4`) is no longer part of the function `specr()` and now has to be specified explicitly if parallelization is desired. 
- `specr()` nonetheless remains conditional on sequential processing (the standard) is set or not. If `is(plan(), "sequential") == TRUE`, it still uses a simple `pmap()` function as this seems to be faster then `future_pmap` in sequential mode. 

## Response to @mscharkow:
- added print generic functions to both S3 classes
- Removed dependency on `tictoc`. Elapsed seconds are also no longer plotted after fitting, but are included in the summary output

## Some other additions/changes:
- Added a generic plot() function for the setup. Not really that important, but can help understanding what one does (we included something similar in earlier versions, so why not)
- Updated all vignettes and examples to reflect the changes outlined above.


From my point of view, it is now ready to be merged. It passed R CMD check (`devtools::check()`), but I now also run the more comprehensive `rhub::check_for_cran()`. If it passes all tests and checks with no errors, warnings, and notes. I would merge and submit to CRAN if you have no further objections.

**Pull request merged**
