### PR TITLE
Parallel processing

### PR DESCRIPTION
**Pull request by mvuorre**
Implements #1 

- [X] Parallelization over specs
- [x] Parallelization over subsets (needs some refactoring)

In addition, what dependencies do we want? The way it is implemented now requires {foreach} to run. It defaults to sequential processing unless user sets

```
library(doParallel)
registerDoParallel(cores=<more than one>)
```

Alternatively, there could be an if else switch in `run_spec()` and `run_specs()` could allow an argument to specify whether to use sequential (default) or parallel processing. This method would reduce dependencies.

### CODE REVIEW

**Comment by masurp** [comment]
Matti!

That's awesome. I have been grappling a bit with how to best solve the issue of the hierarchical structure related to the subset creation. I was also considering using `furrr` the parallel processing extention of `purrr`, which parallels the `map()` functions. Any thoughts on that? Currently a bit busy with other stuff, but happy to work on this with you!?

Hope you're doing well otherwise!

**Comment by mvuorre** [comment]
# 👋 

Happy if I'm able to contribute. I liked how easy the specr functions make it to run many models (soon in parallel 😉).

- I currently implemented parallel processing with the {foreach} package, because passing functions (e.g. model names like `lmer_ri_1` in the multilevel vignette) within a function to `furrr::future_map2()` was not fun. This is liable to change though, because
- I am refactoring the code to put the data frame inside the specs. This would simplify the code a lot (I believe) because then running the specs would be just iterating over one table with no external objects passed in. It would also deprecate everything related to how the subsets are created (they would just be tibbles in the specs table).
- I would like to use [{multidplyr}](https://multidplyr.tidyverse.org/index.html) for the parallel processing if possible because it seems safer (it doesn't create some global setting for parallel processing, but rather you have to specify the cluster and send things to it)

I have an idea of how this might work, but it will introduce some breaking changes, especially in how the subset argument is handled. I might be able to push this soon so you can review and see if it still is in scope of what you have in mind for specr.

cheers :)

**Comment by mvuorre** [comment]
OK I've implemented it here: https://matti.quarto.pub/tidyverse--multidplyr--multiverse--unicorns-and-ice-cream/

As you can see it is quite a departure from the specr codebase. (I did not yet wrap it into a function but hopefully it is somewhat clear.) Some important differences:

- As it is it of course doesn't implement all specr functionality, but this should be easy to add
- The only downside of putting the data in the specs table seems to be that it might get quite large, but it is unlikely that anyone will do this with data frames that are multiple gigs in size! 
- `by` might not exactly work like `subsets`, and doesn't e.g. include an "all" category. That would be pretty easy to include but I don't think it's necessary.
- I didn't yet implement the different ways of combining covariates

It would also be nice to let the user just provide the formulas manually. That would be pretty easy too. So they could either let the function automatically create formulas from `x`, `y`, and `covariate`, or enter more complex ones manually (this could even be a `glue::glue()` call to allow combining the two maybe).

Let me know if this is too far from your vision of specr. At the very least you can use the initial parallelization over specs (but not subsets) since that's a very minor change.

**Comment by mvuorre** [comment]
Hi @masurp, I have a nice `furrr` implementation for multiverse analyses here: https://vuorre.netlify.app/posts/parallel-multiverse/#furrr

I'd be keen to help implement it in the back-end for specr, but that would need refactoring how `run_specs()` works. Currently it either sends the specs to `run_spec()`, or if there are subgroups, then it sends the specs by subgroup to `run_spec()`. In order to use parallel processing efficiently, it should iterate over specs and subgroups in one go. I show how to do that within the function that iterates over a specs table in the blog post. But I think it might be a fairly significant refactor of the specr back end and was wondering if you'd be keen to take it up or think about it a bit?

**Comment by masurp** [comment]
See #32 for an implementation of these ideas in a new version.

**Pull request closed without merging**
